services:
  server:
    build:
      context: .
      dockerfile: ./API/API.Dockerfile
    networks:
      - app-network
    volumes:
      - ./API:/app
      - ./db:/app/db
      - ./config.py:/app/config.py
      - ./schemas:/app/schemas
    env_file: .env
    ports:
      - 8000:8000
  # bot:
  #   ...
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_OUTER_PORT}:${POSTGRES_INNER_PORT}"
    networks:
      - app-network
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro




networks:
  app-network:
    driver: bridge
    